import type { DailyRecord, HealthTargets, PeriodSummary, UserProfile } from '@/apis/health/health.type'
import type { GoalProgress, Recommendation } from '@/apis/goals/goals.type'
import { CALORIE_TOLERANCE, GOAL_LABEL } from '@/constants/health'
import { mean, percentOf } from '@/utils/math'
import { hasNutrition } from './generateHistory'
import { calculateTrend } from './metrics'

export function buildGoalProgress(
  profile: UserProfile,
  summary: PeriodSummary,
  targets: HealthTargets,
  loggedRecords: DailyRecord[],
): GoalProgress[] {
  return profile.goals.map((goal) => {
    switch (goal) {
      case 'increase_activity':
        return {
          goal,
          label: GOAL_LABEL[goal],
          metricLabel: 'Average daily steps',
          current: summary.avgSteps,
          target: targets.steps,
          unit: 'steps',
          percentComplete: percentOf(summary.avgSteps, targets.steps),
        }
      case 'improve_sleep':
        return {
          goal,
          label: GOAL_LABEL[goal],
          metricLabel: 'Average sleep per night',
          current: summary.avgSleepMinutes,
          target: targets.sleepMinutes,
          unit: 'minutes',
          percentComplete: percentOf(summary.avgSleepMinutes, targets.sleepMinutes),
        }
      case 'build_muscle':
        return {
          goal,
          label: GOAL_LABEL[goal],
          metricLabel: 'Average protein intake',
          current: summary.avgProteinG,
          target: targets.proteinG,
          unit: 'g',
          percentComplete: percentOf(summary.avgProteinG, targets.proteinG),
        }
      case 'eat_better':
        return {
          goal,
          label: GOAL_LABEL[goal],
          metricLabel: 'Average water intake',
          current: summary.avgWaterMl,
          target: targets.waterMl,
          unit: 'ml',
          percentComplete: percentOf(summary.avgWaterMl, targets.waterMl),
        }
      case 'lose_weight':
      default: {
        const withinRange = loggedRecords.filter(
          (record) =>
            Math.abs(record.nutrition.calories - targets.calories) <=
            targets.calories * CALORIE_TOLERANCE,
        ).length
        const target = Math.max(loggedRecords.length, 1)
        return {
          goal: 'lose_weight' as const,
          label: GOAL_LABEL.lose_weight,
          metricLabel: 'Days within your calorie target',
          current: withinRange,
          target,
          unit: 'days',
          percentComplete: percentOf(withinRange, target),
        }
      }
    }
  })
}

type RecommendationInput = {
  history: DailyRecord[]
  current: DailyRecord[]
  previous: DailyRecord[]
  summary: PeriodSummary
  targets: HealthTargets
  rangeDays: number
}

/**
 * Fixed rules over the user's own numbers. Deliberately not generated by the
 * model, so the advice on the dashboard is stable and explainable.
 */
export function buildRecommendations(input: RecommendationInput): Recommendation[] {
  const { history, current, previous, summary, targets, rangeDays } = input
  const last7 = history.slice(-7)
  const logged7 = last7.filter(hasNutrition)
  const recommendations: Recommendation[] = []

  const avgSleep7 = mean(last7.map((record) => record.sleep.totalMinutes))
  const sleepGap = targets.sleepMinutes - avgSleep7
  if (sleepGap > 45) {
    recommendations.push({
      id: 'sleep-earlier',
      title: 'Move your bedtime 30 minutes earlier',
      reason: `You averaged ${Math.round(avgSleep7)} minutes of sleep over the last 7 days, ${Math.round(
        sleepGap,
      )} minutes short of your ${targets.sleepMinutes} minute target.`,
      action: 'Pick three weeknights and set a wind-down reminder 30 minutes before your usual bedtime.',
      weight: sleepGap,
    })
  }

  const stepTrend = calculateTrend(
    current.map((record) => record.steps),
    previous.map((record) => record.steps),
  )
  if (stepTrend && stepTrend.changePercent < -10) {
    recommendations.push({
      id: 'steps-recover',
      title: 'Add a short walk on your quietest days',
      reason: `Your average daily steps are down ${Math.abs(
        Math.round(stepTrend.changePercent),
      )}% compared with the previous ${rangeDays} days.`,
      action: 'A 15 minute walk on your three lowest days brings the average back in line.',
      weight: Math.abs(stepTrend.changePercent) * 5,
    })
  }

  const lowProteinDays = logged7.filter(
    (record) => record.nutrition.proteinG < targets.proteinG * 0.8,
  ).length
  if (lowProteinDays >= 4) {
    recommendations.push({
      id: 'protein-breakfast',
      title: 'Add a protein source to breakfast',
      reason: `Protein was below 80% of your ${targets.proteinG} g target on ${lowProteinDays} of the last 7 logged days.`,
      action: 'Eggs, Greek yoghurt or tofu at breakfast typically closes a 20 to 30 g gap.',
      weight: lowProteinDays * 12,
    })
  }

  const avgWater7 = mean(logged7.map((record) => record.nutrition.waterMl))
  if (logged7.length > 0 && avgWater7 < targets.waterMl * 0.7) {
    recommendations.push({
      id: 'hydration',
      title: 'Set two hydration reminders',
      reason: `You averaged ${Math.round(avgWater7)} ml of water over the last 7 logged days against a ${
        targets.waterMl
      } ml target.`,
      action: 'Mid-morning and mid-afternoon reminders are usually enough to close the gap.',
      weight: (targets.waterMl - avgWater7) / 10,
    })
  }

  const hrDelta = summary.avgRestingHeartRate - mean(previous.map((record) => record.restingHeartRate))
  if (previous.length > 0 && hrDelta > 5) {
    recommendations.push({
      id: 'recovery',
      title: 'Plan a lighter training week',
      reason: `Your resting heart rate is up ${Math.round(
        hrDelta,
      )} bpm compared with the previous period, which often follows accumulated fatigue.`,
      action: 'Keep the sessions but drop the intensity for a week, and watch whether it settles.',
      weight: hrDelta * 8,
    })
  }

  const daysAllMet = last7.filter(
    (record) =>
      record.steps >= targets.steps &&
      record.sleep.totalMinutes >= targets.sleepMinutes &&
      (!hasNutrition(record) ||
        Math.abs(record.nutrition.calories - targets.calories) <=
          targets.calories * CALORIE_TOLERANCE),
  ).length
  if (daysAllMet >= 5) {
    recommendations.push({
      id: 'raise-target',
      title: 'Raise your step target by 10%',
      reason: `You met every target on ${daysAllMet} of the last 7 days.`,
      action: `Bumping the daily target to ${Math.round(targets.steps * 1.1)} steps keeps the progress going.`,
      weight: daysAllMet * 6,
    })
  }

  return recommendations.sort((a, b) => b.weight - a.weight).slice(0, 3)
}
